export const API_ROUTES = {
  AUTH: {
    BASE: "/auth",
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    SIGNUP_MANAGER: "/auth/register-manager",
    REFRESH: "/auth/refresh-token",
    LOGOUT: "/auth/logout",
    VERIFY_EMAIL: "/auth/verify-email",
    SEND_OTP: "/auth/send-otp",
    VERIFY_OTP: "/auth/verify-otp",
    COMPLETE_SIGNUP: "/auth/complete-signup",
    RESET_PASSWORD_REQUEST: "/auth/reset-password-request",
    RESET_PASSWORD: "/auth/reset-password",
    ACCEPT_INVITE: "/auth/accept-invite",
    VALIDATE_INVITE: (token: string) => `/auth/invite/${token}`,
    GOOGLE_SIGNIN: "/auth/google-signin",
  },
  ADMIN: {
    BASE: "/admin",
    USERS: "/admin/users",
    ORGANIZATIONS: "/admin/organizations",
    REPORTS: "/admin/reports",
    PLANS: "/admin/plans",
    INVITE_MEMBER: "/admin/invite-member",
    BULK_INVITE: "/admin/bulk-invite",
    INVOICES: "/admin/invoices",
  },
  MANAGER: {
    BASE: "/manager",
    MEMBERS: "/manager/members",
    INVITATIONS: "/manager/invitations",
    INVITE: "/manager/invite-member",
    BULK_INVITE: "/manager/bulk-invite",
    ORGANIZATION: "/manager/organization",
    INVOICES: "/manager/invoices",
  },
  PROJECTS: {
    BASE: "/projects",
    GET_getAll: "/projects",
    CREATE: "/projects",
    GET_MY_PROJECTS: "/projects/my-projects",
    GET_MY_TASKS: "/projects/tasks/my-tasks",
    GET_BY_ID: (id: string) => `/projects/${id}`,
    UPDATE: (id: string) => `/projects/${id}`,
    DELETE: (id: string) => `/projects/${id}`,
    TASKS: (projectId: string) => `/projects/${projectId}/tasks`,
    TASK_UPDATE: (id: string) => `/projects/tasks/${id}`,
    TASK_DELETE: (id: string) => `/projects/tasks/${id}`,
    TASK_TIMER: (id: string) => `/projects/tasks/${id}/timer`,
    TASK_HISTORY: (id: string) => `/projects/tasks/${id}/history`,
    TASK_COMMENTS: (id: string) => `/projects/tasks/${id}/comments`,
    TASK_ATTACHMENTS: (id: string) => `/projects/tasks/${id}/attachments`,
    VELOCITY: (projectId: string) => `/projects/${projectId}/velocity`,
    MEMBERS: (projectId: string) => `/projects/${projectId}/members`,
    SPRINT_CREATE: "/projects/sprints",
    SPRINTS: (projectId: string) => `/projects/${projectId}/sprints`,
    SPRINT_UPDATE: (id: string) => `/projects/sprints/${id}`,
    SPRINT_DELETE: (id: string) => `/projects/sprints/${id}`,
  },
  USER: {
    BASE: "/user",
    PROFILE: "/user/profile",
    CHANGE_PASSWORD: "/user/change-password",
    DELETE_ACCOUNT: "/user/account",
    VELOCITY: "/user/velocity",
  },
  ORG: {
    BASE: "/organization",
    INVITES: "/organization/invites",
    MEMBERS: "/organization/members",
    ME: "/organization/me",
    USERS: "/organization/users",
  },
  PLANS: {
    BASE: "/plans",
    GET_ALL: "/plans",
  },
  WEBHOOKS: {
    BASE: "/webhooks",
    RAZORPAY: "/webhooks/razorpay",
  },
  CHAT: {
    BASE: "/chat",
    SEND: (projectId: string) => `/chat/${projectId}`,
    GET_MESSAGES: (projectId: string) => `/chat/${projectId}`,
    EDIT: (messageId: string) => `/chat/${messageId}`,
    DELETE: (messageId: string) => `/chat/${messageId}`,
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    GET_ALL: "/notifications",
    READ_ALL: "/notifications/read-all",
    READ_ONE: (id: string) => `/notifications/${id}/read`,
  },
  PAYMENT: {
    BASE: "/payments",
    SUBSCRIPTION: "/payments/subscription",
    VERIFY: "/payments/verify",
  },
  UPLOAD: {
    BASE: "/upload",
    FILE: "/upload",
  },
} as const;
